<ul class="<?= $this->navigation()->menu()->getUlClass() ?>">
                    <li class="xn-logo">
                        <a href="/">Net Ops</a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                    <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <img src="/assets/users/martijng.jpg" alt="Martijn Groenleer"/>
                        </a>
                        <div class="profile">
                            <div class="profile-image">
                                <img src="/assets/users/martijng.jpg" alt="Martijn Groenleer"/>
                            </div>
                            <div class="profile-data">
                                <div class="profile-data-name">Martijn Groenleer</div>
                                <div class="profile-data-title">Network Engineer</div>
                            </div>
                            <div class="profile-controls">
                                <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span></a>
                                <a href="pages-messages.html" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                            </div>
                        </div>                                                                        
                    </li>
                    <li class="xn-title">Navigation</li>
    <?php
    // iterate through the pages
    foreach ($this->container as $key => $page):
        ?>
        <li <?php if (count($page->getPages())) { echo 'class="xn-openable"';} ?>>
            <?php
            // if this isn't the last page, add a link and the separator
//            if ($key < count($this->containers) - -1):
                ?>
                <a href="<?php echo $page->getHref(); ?>"><span class="xn-text"><?php echo $page->getLabel(); ?></span><!-- <?php try {echo $page->getImage();}catch(Exception $e){} ?> --></a>
            <?php
            // otherwise, just output the name
//            else:
            ?>
                <?php // echo $page->getLabel(); ?>
            <?php // endif; ?>
 <?php       
  if (count($page->getPages())) {
        echo PHP_EOL."\t<ul>".PHP_EOL;
    foreach ($page->getPages() as $subPage) {
      $active = $subPage->isActive(true);
      echo "\t\t".'<li' .((count($subPage->getPages()))?' class="xn-openable"':'').'>'.PHP_EOL;
        echo "\t\t\t".'<a class="'. ($active ? 'active' : '') .'" href="' . $subPage->getHref() . '">' . $subPage->getLabel() . '</a>'.PHP_EOL;
      echo "\t\t".'</li>'.PHP_EOL; 
    }
        echo "\t"."</ul>".PHP_EOL;
  }
?>       
       </li>
    <?php endforeach; ?>
</ul>
