<?= $this->doctype() ?>
<?php
$this->navigation()->addPage(array(
    'type' => 'uri',
    'label' => 'New page'));
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Net Ops')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        //    ->prependStylesheet($this->basePath('css/style.css'))
        //    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        //    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('themes/joli/css/theme-default.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <!-- START PAGE CONTAINER -->
        <div class="page-container page-navigation-top-fixed <?php /* page-navigation-toggled  page-container-wide */ ?>">
            
            <!-- START PAGE SIDEBAR -->
            <div class="page-sidebar">
                <!-- START X-NAVIGATION -->


    <?php // <-- Add this !!
// <div class="collapse navbar-collapse">
    echo $this->navigation('navigation')->menu()->setMinDepth(0)->setMaxDepth(5)->setUlClass('x-navigation')->setPartial('layout/body/navigation.phtml');
// </div>
    ?>

                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->
            <!-- PAGE CONTENT -->
            <div class="page-content">
                <!-- START X-NAVIGATION VERTICAL -->
                <ul class="x-navigation x-navigation-horizontal x-navigation-panel">
                    <!-- TOGGLE NAVIGATION -->
                    <li class="xn-icon-button">
                        <a class="x-navigation-minimize" href="#"><span class="fa fa-dedent"></span></a>
                    </li>
                    <!-- END TOGGLE NAVIGATION -->
                    <!-- SEARCH -->
                    <li class="xn-search">
                        <form role="form">
                            <input type="text" placeholder="Search..." name="search">
                        </form>
                    </li>   
                    <!-- END SEARCH -->
                    <!-- SIGN OUT -->
                    <li class="xn-icon-button pull-right">
                        <a data-box="#mb-signout" class="mb-control" href="#"><span class="fa fa-sign-out"></span></a>                        
                    </li> 
                    <!-- END SIGN OUT -->
                    <!-- MESSAGES -->
                    <li class="xn-icon-button pull-right">
                        <a href="#"><span class="fa fa-comments"></span></a>
                        <div class="informer informer-danger">4</div>
                        <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging ui-draggable">
                            <div class="panel-heading ui-draggable-handle">
                                <h3 class="panel-title"><span class="fa fa-comments"></span> Messages</h3>                                
                                <div class="pull-right">
                                    <span class="label label-danger">4 new</span>
                                </div>
                            </div>
                            <div style="height: 200px;" class="panel-body list-group list-group-contacts scroll mCustomScrollbar _mCS_2 mCS-autoHide mCS_no_scrollbar"><div class="mCustomScrollBox mCS-light mCSB_vertical mCSB_inside" id="mCSB_2" tabindex="0"><div dir="ltr" style="position:relative; top:0; left:0;" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" id="mCSB_2_container">
                                <a class="list-group-item" href="#">
                                    <div class="list-group-status status-online"></div>
                                    <img alt="John Doe" class="pull-left" src="/themes/joli/assets/images/users/user2.jpg">
                                    <span class="contacts-title">John Doe</span>
                                    <p>Praesent placerat tellus id augue condimentum</p>
                                </a>
                                <a class="list-group-item" href="#">
                                    <div class="list-group-status status-away"></div>
                                    <img alt="Dmitry Ivaniuk" class="pull-left" src="/themes/joli/assets/images/users/user.jpg">
                                    <span class="contacts-title">Dmitry Ivaniuk</span>
                                    <p>Donec risus sapien, sagittis et magna quis</p>
                                </a>
                                <a class="list-group-item" href="#">
                                    <div class="list-group-status status-away"></div>
                                    <img alt="Nadia Ali" class="pull-left" src="/themes/joli/assets/images/users/user3.jpg">
                                    <span class="contacts-title">Nadia Ali</span>
                                    <p>Mauris vel eros ut nunc rhoncus cursus sed</p>
                                </a>
                                <a class="list-group-item" href="#">
                                    <div class="list-group-status status-offline"></div>
                                    <img alt="Darth Vader" class="pull-left" src="/themes/joli/assets/images/users/user6.jpg">
                                    <span class="contacts-title">Darth Vader</span>
                                    <p>I want my money back!</p>
                                </a>
                            </div><div class="mCSB_scrollTools mCSB_2_scrollbar mCS-light mCSB_scrollTools_vertical" id="mCSB_2_scrollbar_vertical" style="display: none;"><div class="mCSB_draggerContainer"><div oncontextmenu="return false;" style="position: absolute; min-height: 30px; top: 0px;" class="mCSB_dragger" id="mCSB_2_dragger_vertical"><div class="mCSB_dragger_bar" style="line-height: 30px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div></div>     
                            <div class="panel-footer text-center">
                                <a href="pages-messages.html">Show all messages</a>
                            </div>                            
                        </div>                        
                    </li>
                    <!-- END MESSAGES -->
                    <!-- TASKS -->
                    <li class="xn-icon-button pull-right">
                        <a href="#"><span class="fa fa-tasks"></span></a>
                        <div class="informer informer-warning">3</div>
                        <div class="panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging ui-draggable">
                            <div class="panel-heading ui-draggable-handle">
                                <h3 class="panel-title"><span class="fa fa-tasks"></span> Tasks</h3>                                
                                <div class="pull-right">
                                    <span class="label label-warning">3 active</span>
                                </div>
                            </div>
                            <div style="height: 200px;" class="panel-body list-group scroll mCustomScrollbar _mCS_3 mCS-autoHide mCS_no_scrollbar"><div class="mCustomScrollBox mCS-light mCSB_vertical mCSB_inside" id="mCSB_3" tabindex="0"><div dir="ltr" style="position:relative; top:0; left:0;" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y" id="mCSB_3_container">                                
                                <a href="#" class="list-group-item">
                                    <strong>Phasellus augue arcu, elementum</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div style="width: 50%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" role="progressbar" class="progress-bar progress-bar-danger">50%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 25 Sep 2014 / 50%</small>
                                </a>
                                <a href="#" class="list-group-item">
                                    <strong>Aenean ac cursus</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div style="width: 80%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-warning">80%</div>
                                    </div>
                                    <small class="text-muted">Dmitry Ivaniuk, 24 Sep 2014 / 80%</small>
                                </a>
                                <a href="#" class="list-group-item">
                                    <strong>Lorem ipsum dolor</strong>
                                    <div class="progress progress-small progress-striped active">
                                        <div style="width: 95%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="95" role="progressbar" class="progress-bar progress-bar-success">95%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 23 Sep 2014 / 95%</small>
                                </a>
                                <a href="#" class="list-group-item">
                                    <strong>Cras suscipit ac quam at tincidunt.</strong>
                                    <div class="progress progress-small">
                                        <div style="width: 100%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" role="progressbar" class="progress-bar">100%</div>
                                    </div>
                                    <small class="text-muted">John Doe, 21 Sep 2014 /</small><small class="text-success"> Done</small>
                                </a>                                
                            </div><div class="mCSB_scrollTools mCSB_3_scrollbar mCS-light mCSB_scrollTools_vertical" id="mCSB_3_scrollbar_vertical" style="display: none;"><div class="mCSB_draggerContainer"><div oncontextmenu="return false;" style="position: absolute; min-height: 30px; top: 0px;" class="mCSB_dragger" id="mCSB_3_dragger_vertical"><div class="mCSB_dragger_bar" style="line-height: 30px;"></div></div><div class="mCSB_draggerRail"></div></div></div></div></div>     
                            <div class="panel-footer text-center">
                                <a href="pages-tasks.html">Show all tasks</a>
                            </div>                            
                        </div>                        
                    </li>
                    <!-- END TASKS -->
                </ul>
                <!-- END X-NAVIGATION VERTICAL -->


                <!-- START BREADCRUMB -->
		<?php

			echo $this->navigation('navigation')
          ->breadcrumbs()
          ->setLinkLast(true)                   // link last page
          ->setMinDepth(0)/*
          ->setMaxDepth(false)*/                      // stop at level 1
          ->setPartial('layout/body/breadcrumbs.phtml');
// */
		?>                 
                <!-- END BREADCRUMB -->                       
                
                <!-- START PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">
	            <?= $this->content ?>

                </div>  
                <!-- END PAGE CONTENT WRAPPER -->
            </div>           
	</div>


        <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> Log <strong>Out</strong> ?</div>
                    <div class="mb-content">
                        <p>Are you sure you want to log out?</p>                    
                        <p>Press No if youwant to continue work. Press Yes to logout current user.</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <a href="pages-login.html" class="btn btn-success btn-lg">Yes</a>
                            <button class="btn btn-default btn-lg mb-control-close">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->


<!--
        <div class="container">
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
-->


        <?= $this->inlineScript() ?>

        <!-- START PRELOADS -->
        <audio id="audio-alert" src="/themes/joli/audio/alert.mp3" preload="auto"></audio>
        <audio id="audio-fail" src="/themes/joli/audio/fail.mp3" preload="auto"></audio>
        <!-- END PRELOADS -->                  
        
    <!-- START SCRIPTS -->
        <!-- START PLUGINS -->
        <script type="text/javascript" src="/themes/joli/js/plugins/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="/themes/joli/js/plugins/jquery/jquery-ui.min.js"></script>
        <script type="text/javascript" src="/themes/joli/js/plugins/bootstrap/bootstrap.min.js"></script>        
        <!-- END PLUGINS -->

        <!-- START THIS PAGE PLUGINS-->        
        <script type='text/javascript' src="/themes/joli/js/plugins/icheck/icheck.min.js"></script>        
        <script type="text/javascript" src="/themes/joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
        <script type="text/javascript" src="/themes/joli/js/plugins/scrolltotop/scrolltopcontrol.js"></script>
        
        <script type="text/javascript" src="/themes/joli/js/plugins/morris/raphael-min.js"></script>
        <script type="text/javascript" src="/themes/joli/js/plugins/morris/morris.min.js"></script>       
        <script type="text/javascript" src="/themes/joli/js/plugins/rickshaw/d3.v3.js"></script>
        <script type="text/javascript" src="/themes/joli/js/plugins/rickshaw/rickshaw.min.js"></script>
        <script type='text/javascript' src="/themes/joli/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
        <script type='text/javascript' src="/themes/joli/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>                
        <script type='text/javascript' src="/themes/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>                
        <script type="text/javascript" src="/themes/joli/js/plugins/owl/owl.carousel.min.js"></script>                 
        
        <script type="text/javascript" src="/themes/joli/js/plugins/moment.min.js"></script>
        <script type="text/javascript" src="/themes/joli/js/plugins/daterangepicker/daterangepicker.js"></script>
        <!-- END THIS PAGE PLUGINS-->        

        <!-- START TEMPLATE -->
<?php
//        <script type="text/javascript" src="/themes/joli/js/settings.js"></script>
  ?>      
        <script type="text/javascript" src="/themes/joli/js/plugins.js"></script>        
        <script type="text/javascript" src="/themes/joli/js/actions.js"></script>
        
        <script type="text/javascript" src="/themes/joli/js/demo_dashboard.js"></script>
        <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->         

    </body>
</html>
